; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:featheresp32]
platform = espressif32
; board = featheresp32
board = esp32-s3-devkitc-1
; board = esp32-s3-devkitm-1
framework = arduino
board_microros_transport = wifi
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
lib_deps = 
	https://github.com/fishros/Esp32McpwmMotor.git
	https://gitee.com/ohhuo/micro_ros_platformio.git
	https://github.com/fishros/Esp32PcntEncoder.git
	dfrobot/DFRobot_RTU@^1.0.3
	tockn/MPU6050_tockn@^1.5.2
	hideakitai/MPU9250@^0.4.8
	adafruit/Adafruit SSD1306@^2.5.11
	arminjo/PWMMotorControl@^2.1.0
	kroia/L298N_MotorDriver@^1.0.1

; [env:featheresp32]
; platform = espressif32
; ; board = esp32s3_powerfeather
; board = featheresp32
; framework = arduino
; board_microros_transport = wifi

; board_build.f_cpu = 240000000L
; board_build.f_flash = 80000000L
; lib_deps = 
; 	https://github.com/fishros/Esp32McpwmMotor.git
; 	https://gitee.com/ohhuo/micro_ros_platformio.git
; 	https://github.com/fishros/Esp32PcntEncoder.git
; 	dfrobot/DFRobot_RTU@^1.0.3
; 	tockn/MPU6050_tockn@^1.5.2
; 	hideakitai/MPU9250@^0.4.8
; 	adafruit/Adafruit SSD1306@^2.5.11
; 	arminjo/PWMMotorControl@^2.1.0
; 	kroia/L298N_MotorDriver@^1.0.1
